[package]
name = "algoliasearch"
version = "0.1.0"
authors = ["Nicolas Barbotte <nicolas@barbotte.net>"]
edition = "2018"
description = "Algolia client"
keywords = ["algolia", "client", "search"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/nicompte/algoliasearch-rs"
homepage = "https://github.com/nicompte/algoliasearch-rs"
documentation = "https://doc.barbotte.net/algoliasearch"
include = [
    "src/**/*",
    "Cargo.toml",
]

[dependencies]
derive_builder = "0.7.1"
futures = "0.1.26"
reqwest = "0.9.13"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
serde_repr = "0.1.3"
serde_urlencoded = "0.5.4"
tokio = "0.1.18"
chrono = { version = "0.4.6", features = ["serde"] }
